filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/chat_message.log  # Path inside container

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug