name: Deploy Go Chat App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: malektih/go-chat-app:1.0.0

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull malektih/go-chat-app:1.0.0
      - name: Delete old docker container
        run: docker rm -f go-chat-app || true
      - name: Run new docker container
        run: |
          docker run -d \
          -p 8080:8080 \
          -p 4000:4000 \
          --name go-chat-app \
          -e DB_HOST="${{ secrets.DB_HOST }}" \
          -e DB_PORT="${{ secrets.DB_PORT }}" \
          -e DB_NAME="${{ secrets.DB_NAME }}" \
          -e DB_USER="${{ secrets.DB_USER }}" \
          -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          -e APP_NAME="GoChatApp" \
          -e APP_HOST="0.0.0.0" \
          -e APP_PORT="4000" \
          -e APP_PORT_SOCKET="8080" \
          -e APP_SECRET="${{ secrets.APP_SECRET }}" \
          -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          -e ELASTIC_APM_SERVER_URL="${{ secrets.ELASTIC_APM_SERVER_URL }}" \
          malektih/go-chat-app:1.0.0